name: Continuous Integration

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Maven
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn package
    - name: Deploy to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        mvn -B -e -Dmaven.wagon.http.pool=false deploy
